route:
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: hangouts-chat-webhook

receivers:
  - name: 'hangouts-chat-webhook'
    webhook_configs:
      # Send alert to hangout's room
      - url: 'http://alertmanager-hangouts-chat.webhooks.svc:8080/api/v1/hangout?auth_token=YOUR_TOKEN&url_hangout=YOUR_URL_HANGOUTS_ROOM'
