########################################################################################################
# Descripcion: Namespace webhooks
########################################################################################################

# Main
#*******************************************************************************************************
apiVersion: v1
kind: Namespace

metadata:
  name: webhooks
#*******************************************************************************************************
